<a href="https://colab.research.google.com/github/shubham-dalmia/numpy-exercises/blob/main/numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) to import numpy

In [ ]:
import numpy as np

2) Print the numpy version and the configuration

In [ ]:
print(np.__version__)
print(np.show_config)

1.19.5
<function show at 0x7f5174ceb4d0>


3) Create a null vector of size 10

In [ ]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4) How to find the memory size of any array 

In [ ]:
a=np.array([1,2,3])
a.nbytes

24


5) How to get the documentation of the numpy add function from the command line? 

In [ ]:
print(np.info(np.add))

None


6) Create a null vector of size 10 but the fifth value which is 1

In [ ]:
b=np.zeros(10)
b[4,]=1;
print(b)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7) Create a vector with values ranging from 10 to 49

In [ ]:
c=np.arange(10,49)
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


8)Reverse a vector (first element becomes last)

In [ ]:
print(c[-1:-40:-1])

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9)Create a 3x3 matrix with values ranging from 0 to 8 

In [ ]:
d=np.arange(0,9).reshape(3,3)
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10) Find indices of non-zero elements from [1,2,0,0,4,0]

In [ ]:
e=np.array([1,2,0,0,4,0])
for i in range(len(e)):
     if e[i]!=0:
        print(i)

0
1
4


11)Create a 3x3 identity matrix

In [ ]:
print(np.identity(3,dtype='int32'))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


12)Create a 3x3x3 array with random values

In [ ]:
print(np.random.rand(3,3,3))

[[[0.52740697 0.64299196 0.03598369]
  [0.66017622 0.9941713  0.26590271]
  [0.42320377 0.24122374 0.3113004 ]]

 [[0.45983194 0.81875446 0.99169373]
  [0.29061521 0.08145469 0.13578218]
  [0.88431115 0.97176017 0.92058328]]

 [[0.52894537 0.87439679 0.67385587]
  [0.13244182 0.94112283 0.86230331]
  [0.82235704 0.22878523 0.82387555]]]


13)Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
f=np.random.rand(10,10)
min=f.min()
max=f.max()
print(f)
print(min)
print(max)


[[0.22610494 0.75537559 0.79745473 0.18884226 0.7623684  0.77776657
  0.65283016 0.36458043 0.81441128 0.23309204]
 [0.70311219 0.66912722 0.44364541 0.72489534 0.15807912 0.20049077
  0.97478835 0.96461937 0.35733509 0.40940943]
 [0.34857409 0.59131209 0.52360525 0.30467805 0.68056934 0.47493311
  0.85445993 0.25074865 0.201182   0.08543881]
 [0.19291554 0.51974405 0.42857891 0.78960636 0.94135241 0.16652318
  0.65979283 0.00461589 0.18870715 0.28248647]
 [0.10491145 0.79369858 0.51459184 0.74499814 0.96783894 0.87579829
  0.97048693 0.69798608 0.27321257 0.77047661]
 [0.69179368 0.34999132 0.85060821 0.33412614 0.74292031 0.04839955
  0.68570919 0.47290708 0.2181544  0.59139107]
 [0.84993531 0.93656943 0.79584188 0.63507169 0.48768032 0.29047956
  0.2362575  0.53391087 0.03417466 0.15275754]
 [0.05197435 0.3023833  0.50904365 0.02329525 0.88110024 0.47518685
  0.93251587 0.93218714 0.90121597 0.83926691]
 [0.24476332 0.61381229 0.36469029 0.58088958 0.0437299  0.4047155
  0.07914418 

14) Create a random vector of size 30 and find the mean value 

In [ ]:
a=np.random.rand(8)
print(a)
print(a.mean())

[0.18821805 0.38625419 0.57326453 0.64014281 0.50094707 0.14541597
 0.15590523 0.66890481]
0.4073815819945463


15)Create a 2d array with 1 on the border and 0 inside 

In [ ]:
a=np.ones((5,5))
b=np.zeros((3,3))
a[1:-1,1:-1]=b
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


16)How to add a border (filled with 0's) around an existing array?

In [ ]:
a=np.full((2,2),2)
print(a)
b=np.zeros((4,4))
b[1:-1,1:-1]=a
print(b)

[[2 2]
 [2 2]]
[[0. 0. 0. 0.]
 [0. 2. 2. 0.]
 [0. 2. 2. 0.]
 [0. 0. 0. 0.]]


17) What is the result of the following expression? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

18) Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
a=np.zeros((5,5))
for i in range(4):
  a[i+1,i]=i+1
print(a)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


19)Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
a=np.zeros((8,8), dtype='int32')
a[0:8:2,0:8:2]=1
a[1:9:2,1:9:2]=1
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


20)Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


21) Create a checkerboard 8x8 matrix using the tile function 

In [ ]:
arr=np.array([[0, 1], [1, 0]])
print(np.tile(arr,(4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22) Normalize a 5x5 random matrix

In [ ]:
a=np.random.rand(5,5)
a=(a-np.mean(a))/(np.std(a))
print(a)

[[ 0.89792092  0.96639838 -1.22418248  1.42010344  0.74317409]
 [-0.32228424  1.52135189  1.52448575 -0.91266949 -0.67731946]
 [-0.80929646 -0.75525392 -0.40066925  0.61395219 -1.45406951]
 [ 0.85234442  0.50922339  1.15788156  0.71068063 -0.77741681]
 [-0.79951972  0.69114052 -0.47646786 -1.46454818 -1.53495981]]


23)Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [ ]:
color = np.dtype([("r", np.ubyte, (1,)),
                  ("g", np.ubyte, (1,)),
                  ("b", np.ubyte, (1,)),
                  ("a", np.ubyte, (1,))])


24)Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [ ]:
a=np.full((5,3),2)
b=np.full((3,2),7)
print(np.matmul(a,b))

[[42 42]
 [42 42]
 [42 42]
 [42 42]
 [42 42]]


25) Given a 1D array, negate all elements which are between 3 and 8, in place. 

In [ ]:
a = np.arange(10)
a[(a >= 3) & (a<= 8)] = 0
print(a)

[0 1 2 0 0 0 0 0 0 9]


26. What is the output of the following script? 
 Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


9
10


27) Consider an integer vector Z, which of these expressions are legal? 
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

In [ ]:
Z=1
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

1
1
False
1j
1.0
False


28) What are the result of the following expressions?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

In [ ]:
import numpy as np
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([-9.22337204e+18])


29)How to round away from zero a float array ? 

In [ ]:
a=np.array([1.2,9.9,8.8,0.119])
print(np.round(a,0))

[ 1. 10.  9.  0.]


30) How to find common values between two arrays? 

In [ ]:
a=np.array([1,2,3,4])
b=np.array([3,4,5,6])
print(np.intersect1d(a,b))

[3 4]


31)How to ignore all numpy warnings (not recommended)? 

In [ ]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

32)Is the following expressions true? 
np.sqrt(-1) == np.emath.sqrt(-1)

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

33)How to get the dates of yesterday, today and tomorrow?

In [ ]:
import datetime 
print( "today",np.datetime64('today','D'))
print("yesterday",np.datetime64('today','D')-np.timedelta64(1,'D'))
print("tommorow",np.datetime64('today','D')+np.timedelta64(1,'D'))


today 2021-09-02
yesterday 2021-09-01
tommorow 2021-09-03
